apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonete-app
  labels:
    app: svc-lanchonete-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32000
  selector:
    app: pod-lanchonete-app